name: 'Build releases'

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows

    strategy:
      matrix:
        node-version: [16.x]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm i
    - name: Check lint
      run: npm run lint
    - name: Build Windows app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run gh-publish-windows

  build-linux:
    name: Build Linux

    strategy:
      matrix:
        node-version: [16.x]

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm i
    - name: Check lint
      run: npm run lint
    - name: Build Linux app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run gh-publish-linux

  build-mac:
    name: Build Mac

    strategy:
      matrix:
        node-version: [16.x]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm i
    - name: Check lint
      run: npm run lint
    - name: Build Mac app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run gh-publish-mac
